/* Given a string, we have to find out all its subsequence of it.
  * A string is a subsequence of a given string, that is generated by deleting some character of a given string without   * changing its order.
  */

#include<iostream>
#include<vector>
using namespace std;

void subsequence(string &str, int i, string result, vector <string> &li){
    if(i == str.length()){
        li.push_back(result);
        return;
    }
    subsequence(str, i + 1, result + str[i], li);
    subsequence(str, i + 1, result, li);
}

   int main(){
    vector<string> res;
    string str = "abc";
    subsequence(str, 0, "", res);
    for(int i = 0; i < res.size(); i++){
        cout << res[i] << " ";
    }

   return 0;
}